id: A0626F20F
base_file: fB0D9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:04:44.777622
  last_modified_at: 2022-05-31 05:04:44.777626
