id: A0626F20F
base_file: f9783.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:04:44.774650
  last_modified_at: 2022-05-31 05:04:44.774654
