id: A0626F20F
base_file: f454E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:04:44.772603
  last_modified_at: 2022-05-31 05:04:44.772611
